-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 18:33:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema task_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_manager` DEFAULT CHARACTER SET utf8 ;
USE `task_manager` ;

-- -----------------------------------------------------
-- Table `task_manager`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_manager`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(40) NOT NULL,
  `apellido_usuario` VARCHAR(40) NOT NULL,
  `telefono_usuario` VARCHAR(12) NOT NULL,
  `direccion_usuario` VARCHAR(45) NOT NULL,
  `correo_usuario` VARCHAR(20) NOT NULL,
  `password_usuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task_manager`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_manager`.`tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `desc_tarea` VARCHAR(45) NOT NULL,
  `fecha_tarea` VARCHAR(15) NOT NULL,
  `estado_tarea` CHAR(1) NOT NULL,
  `id_recurso` VARCHAR(2) NOT NULL,
  `desc_recurso` VARCHAR(30) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_tarea_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_tarea_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `task_manager`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
